services:
  backend:
    build: ./backend
    image: kindle_app-backend:latest
    container_name: kindle_backend
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    image: kindle_app-frontend:latest
    container_name: kindle_frontend
    ports:
      - "8686:80"
    depends_on:
      - backend
    restart: always